title: Stelsel van energieregisters | Netbeheer Nederland
theme: just-the-docs
baseurl: /stelsel

collections:
  registers:
    output: true

just_the_docs:
  collections:
    registers:
      name: Registers

defaults:
  - scope:
      path: ""
    values:
      layout: default

color_scheme: nbnl
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.png"

callouts:
  note:
    color: purple

aux_links:
  "Modellen van Netbeheer Nederland":
    - "https://modellen.netbeheernederland.nl"
