title: Stelsel van energieregisters | Netbeheer Nederland
theme: just-the-docs
baseurl: /stelsel

collections:
  registers:
    output: true

just_the_docs:
  collections:
    registers:
      name: Registers

defaults:
  - scope:
      path: ""
    values:
      layout: default

color_scheme: nbnl
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.png"

callouts:
  note:
    color: purple

aux_links:
  "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"currentColor\" style=\"height:1rem; margin-right:0.5em; margin-bottom:0.1rem\"><path d=\"M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.05-.015-2.07-3.345.72-4.05-1.605-4.05-1.605-.54-1.38-1.335-1.755-1.335-1.755-1.095-.75.09-.735.09-.735 1.215.09 1.845 1.245 1.845 1.245 1.08 1.86 2.835 1.32 3.525 1.005.105-.78.42-1.32.765-1.62-2.67-.3-5.475-1.335-5.475-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405 1.02 0 2.04.135 3 .405 2.28-1.56 3.285-1.245 3.285-1.245.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.285 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z\"/></svg>Broncode":
    - "https://github.com/netbeheer-nederland/stelsel"
  "<img src=\"/assets/images/favicon.png\" style=\"height:1rem; margin-right:0.5em; margin-bottom:0.1rem\" />Modellen":
    - "https://modellen.netbeheernederland.nl"
